# Generated by Django 4.1.2 on 2023-02-12 05:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generos_filmes', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Myflix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('nome_filme', models.CharField(max_length=200)),
                ('sinospse', models.TextField(max_length=500)),
                ('elenco', models.TextField(max_length=200)),
                ('tempo_filme', models.IntegerField(null=True)),
                ('lancamento', models.CharField(max_length=20, null=True)),
                ('classificacao', models.CharField(max_length=20, null=True)),
                ('id_video', models.CharField(max_length=20, null=True)),
                ('capa_filme', models.ImageField(null=True, upload_to='banners')),
                ('publicada', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyflixApp.genero')),
            ],
        ),
    ]
