# Generated by Django 4.1.1 on 2022-09-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myflix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_filme', models.CharField(max_length=200)),
                ('elenco', models.TextField(max_length=100)),
                ('sinospse', models.TextField()),
            ],
        ),
    ]
