# Generated by Django 4.1.1 on 2022-09-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myflix',
            name='sinosps',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myflix',
            name='sinospse',
            field=models.TextField(max_length=200),
        ),
    ]
