# Generated by Django 4.1.1 on 2022-09-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0002_myflix_sinosps_alter_myflix_sinospse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myflix',
            name='sinosps',
        ),
        migrations.AddField(
            model_name='myflix',
            name='capa_filme',
            field=models.ImageField(null=True, upload_to='banners'),
        ),
        migrations.AddField(
            model_name='myflix',
            name='filme',
            field=models.FileField(null=True, upload_to='filme/%y'),
        ),
        migrations.AddField(
            model_name='myflix',
            name='tempo_filme',
            field=models.IntegerField(null=True),
        ),
    ]
