# Generated by Django 4.1.1 on 2022-09-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0003_remove_myflix_sinosps_myflix_capa_filme_myflix_filme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myflix',
            name='filme',
            field=models.FileField(upload_to='filme/%y'),
        ),
    ]
