# Generated by Django 4.1.1 on 2022-09-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0005_myflix_genero_filme_alter_myflix_filme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero_filme', models.CharField(choices=[('Terror', 'Terror'), ('Ação', 'Ação'), ('Suspense', 'Suspense'), ('Ficção', 'Ficção'), ('Policial', 'Policial')], max_length=20, null=True)),
            ],
        ),
    ]
