# Generated by Django 4.1.1 on 2022-09-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0006_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myflix',
            name='genero_filme',
        ),
    ]
