# Generated by Django 4.1.1 on 2022-09-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0007_remove_myflix_genero_filme'),
    ]

    operations = [
        migrations.AddField(
            model_name='myflix',
            name='genero_filme',
            field=models.CharField(choices=[('Terror', 'Terror'), ('Ação', 'Ação'), ('Suspense', 'Suspense'), ('Ficção', 'Ficção'), ('Policial', 'Policial')], max_length=20, null=True),
        ),
    ]
