# Generated by Django 4.1.1 on 2022-09-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0008_myflix_genero_filme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
