# Generated by Django 4.1.1 on 2022-09-23 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0009_delete_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero_filme', models.CharField(choices=[('Terror', 'Terror'), ('Ação', 'Ação'), ('Suspense', 'Suspense'), ('Ficção', 'Ficção'), ('Policial', 'Policial')], max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='myflix',
            name='genero_filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyflixApp.genero'),
        ),
    ]
