# Generated by Django 4.1.1 on 2022-09-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0010_genero_alter_myflix_genero_filme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myflix',
            name='genero_filme',
        ),
        migrations.AddField(
            model_name='myflix',
            name='genero_filme',
            field=models.ManyToManyField(to='MyflixApp.genero'),
        ),
    ]
