# Generated by Django 4.1.1 on 2022-09-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0016_alter_myflix_genero_filme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myflix',
            name='genero_filme',
        ),
    ]
