# Generated by Django 4.1.1 on 2022-09-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0018_filme_remove_myflix_filme_myflix_filme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myflix',
            name='filme',
        ),
        migrations.AddField(
            model_name='myflix',
            name='file_video',
            field=models.FileField(null=True, upload_to='filme'),
        ),
        migrations.AddField(
            model_name='myflix',
            name='generos_filmes',
            field=models.CharField(choices=[('terror', 'Terror'), ('Suspense', 'Suspense'), ('Ação', 'Ação'), ('Ficção', 'Ficção')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Filme',
        ),
    ]
