# Generated by Django 4.1.1 on 2022-09-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0019_remove_myflix_filme_myflix_file_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generos_filmes', models.CharField(choices=[('terror', 'Terror'), ('Suspense', 'Suspense'), ('Ação', 'Ação'), ('Ficção', 'Ficção')], max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='myflix',
            name='generos_filmes',
        ),
        migrations.AddField(
            model_name='myflix',
            name='gener',
            field=models.ManyToManyField(to='MyflixApp.genero'),
        ),
    ]
