# Generated by Django 4.1.2 on 2022-10-05 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0021_alter_genero_generos_filmes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myflix',
            name='gener',
        ),
        migrations.AddField(
            model_name='myflix',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MyflixApp.genero'),
        ),
    ]
