# Generated by Django 4.1.2 on 2022-10-12 20:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0023_myflix_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='myflix',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
