# Generated by Django 4.1.2 on 2022-10-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0024_myflix_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='myflix',
            name='slug',
            field=models.SlugField(default='page-slug', max_length=150, unique=True),
        ),
    ]
