# Generated by Django 4.1.2 on 2022-10-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0025_myflix_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myflix',
            name='slug',
            field=models.SlugField(default='page', max_length=150, unique=True),
        ),
    ]
