# Generated by Django 4.1.2 on 2022-10-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0026_alter_myflix_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myflix',
            name='slug',
            field=models.SlugField(max_length=150),
        ),
    ]
