# Generated by Django 4.1.2 on 2022-10-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0027_alter_myflix_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myflix',
            name='slug',
        ),
        migrations.AddField(
            model_name='myflix',
            name='banner',
            field=models.ImageField(null=True, upload_to='banners'),
        ),
    ]
