# Generated by Django 4.1.2 on 2022-10-14 02:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0028_remove_myflix_slug_myflix_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myflix',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f7cba1ec-03c7-4a04-9b4a-4bb9af5e7cbb')),
        ),
    ]
