# Generated by Django 4.1.2 on 2022-10-15 17:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0030_alter_myflix_elenco_alter_myflix_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myflix',
            name='sinospse',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='myflix',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8216c4f4-afe4-41e4-99e0-96a4d9459426')),
        ),
    ]
