# Generated by Django 4.1.2 on 2022-10-15 19:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0032_remove_myflix_banner_myflix_classificacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myflix',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
