# Generated by Django 4.1.2 on 2022-10-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0033_alter_myflix_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='myflix',
            name='video_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
