# Generated by Django 4.1.2 on 2022-10-16 02:07

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0034_myflix_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myflix',
            name='video_url',
        ),
        migrations.AddField(
            model_name='myflix',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=''),
            preserve_default=False,
        ),
    ]
