# Generated by Django 4.1.2 on 2022-10-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0036_remove_myflix_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='myflix',
            name='id_video',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
