# Generated by Django 4.1.2 on 2022-10-16 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyflixApp', '0037_myflix_id_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myflix',
            name='file_video',
        ),
    ]
